#!/bin/bash

echo "Installing dependencies."
npm install mongodb

echo "This script will restore your Mongo databases from dbs.zip"
echo "Unzipping dbs.zip"
unzip dbs.zip

echo "Finding databases dumps in $PWD/dump"
dbs=`ls dump`

# Import databases
echo "Restoring databases..."
mongorestore ./dump/

echo "Removing obsole directory."
rm -rf dump

echo "Done."
